import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../dist/js/engine.js';import {createWorld,moveEntity,distance,seeded} from '../dist/js/world.js';import {rollChoices,SKILLS,MAX_ENEMIES,MAX_PARTICLES} from '../dist/js/data.js';
function fresh(){const g=new Game({seed:42});g.reset(42);g.spawnClock=1000;return g}
function tick(g,seconds,input){for(let i=0;i<seconds*60;i++)g.step(1/60,input)}
test('same seed reproduces terrain; different seeds change it; spawn clearing is safe',()=>{const a=createWorld(42),b=createWorld(42),c=createWorld(43);assert.deepEqual(a.obstacles,b.obstacles);assert.notDeepEqual(a.obstacles,c.obstacles);assert.ok(a.obstacles.length>60);for(const o of a.obstacles)assert.ok(Math.hypot(o.x-1200,o.y-1200)>210)});
test('movement collides with terrain and world borders',()=>{const w=createWorld(42),o=w.obstacles[0],e={x:o.x-o.r-14,y:o.y,r:13};moveEntity(e,20,0,w);assert.ok(distance(e,o)>=e.r+o.r-.001);moveEntity(e,-10000,0,w);assert.ok(e.x>=e.r)});
test('auto fire damages enemies and kills drop collectible experience',()=>{const g=fresh();g.spawn('crawler',1290,1200);tick(g,2);assert.equal(g.kills,1);assert.ok(g.gems.length||g.player.xp>0)});
test('enemy melee AI attacks and invulnerability blocks repeated damage',()=>{const g=fresh();g.player.attackRate=.01;g.castClocks=[100,100,100];g.spawn('crawler',1225,1200);tick(g,2);assert.ok(g.player.hp<100);const hp=g.player.hp;g.player.invincible=1;g.hurt(10);assert.equal(g.player.hp,hp)});
test('ranged enemies telegraph then fire projectiles',()=>{const g=fresh();g.castClocks=[100,100,100];g.spawn('shaman',1400,1200);tick(g,3);assert.ok(g.hostile.length>0)});
test('level up freezes world, offers three unique choices and applies selection once',()=>{const g=fresh();g.player.xp=12;const level=g.player.level;g.checkLevel();assert.equal(g.state,'levelup');assert.equal(g.player.level,level+1);assert.equal(g.player.xp,0);assert.equal(g.choices.length,3);assert.equal(new Set(g.choices.map(c=>c.id)).size,3);const time=g.time;tick(g,1);assert.equal(g.time,time);const reward=g.choices[0];assert.equal(g.choose(0),true);assert.ok(g.bag[reward.kind].includes(reward.id));assert.equal(g.choose(0),false);assert.equal(g.state,'playing')});
test('multi projectile makes three fireballs; rarity sampling covers all tiers',()=>{const g=fresh();g.links[0].supports[0]='multi';g.spawn('brute',1350,1200);g.shoot();assert.equal(g.shots.length,3);const tiers=new Set(),rng=seeded(4);for(let i=0;i<100;i++)rollChoices(rng).forEach(c=>tiers.add(c.rarity));assert.equal(tiers.size,3)});
test('boss spawns on wave five, attacks, then offers loot after level rewards',()=>{const g=fresh();g.wave=5;g.step(1/60);assert.ok(g.boss);g.player.invincible=100;tick(g,5);assert.ok(g.hostile.length||g.zones.length);g.hitEnemy(g.boss,100000);while(g.state==='levelup')assert.equal(g.choose(0),true);assert.equal(g.state,'reward');assert.ok(g.rewardOptions.length===3);g.takeReward(0);assert.ok(['camp','forge'].includes(g.state))});
test('death, pause and restart isolate run state',()=>{const g=fresh();g.pause();const t=g.time;g.step(.05);assert.equal(t,g.time);g.pause();g.hurt(200);assert.equal(g.state,'dead');g.reset(5);assert.equal(g.player.hp,100);assert.equal(g.kills,0);assert.equal(g.hostile.length,0);assert.equal(g.state,'playing')});
test('dash grants short invulnerability and respects cooldown',()=>{const g=fresh();assert.equal(g.dash(),true);assert.equal(g.dash(),false);g.hurt(50);assert.equal(g.player.hp,100);tick(g,3.1);assert.equal(g.dash(),true)});
test('wave simulation stays bounded with combat and repeated upgrades',()=>{const g=fresh();g.spawnClock=0;g.player.maxHp=100000;g.player.hp=100000;for(let i=0;i<60*230;i++){const a=i/60*.08;g.step(1/60,{x:0,y:0});if(g.state==='levelup')g.choose(0)}assert.ok(g.kills>0);assert.ok(g.player.level>1);assert.ok(g.enemies.length<=MAX_ENEMIES+1);assert.ok(g.particles.length<=MAX_PARTICLES);assert.ok(g.hostile.length<=220);assert.ok(Number.isFinite(g.player.x));});
