import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../dist/js/engine.js';import {createWorld,moveEntity,distance,seeded} from '../dist/js/world.js';import {rollChoices,SKILLS,MAX_ENEMIES,MAX_PARTICLES} from '../dist/js/data.js';import {ENEMY_STATES} from '../dist/js/ai.js';import {BOSS_PHASES,bossCooldown,bossWindup} from '../dist/js/boss.js';import {getActiveSynergies,getSynergyModifiers} from '../dist/js/synergies.js';import {createEncounters,getEncounterPresentation} from '../dist/js/encounters.js';
function fresh(){const g=new Game({seed:42});g.reset(42);g.spawnClock=1000;return g}
function tick(g,seconds,input){for(let i=0;i<seconds*60;i++)g.step(1/60,input)}
test('same seed reproduces terrain; different seeds change it; spawn clearing is safe',()=>{const a=createWorld(42),b=createWorld(42),c=createWorld(43);assert.deepEqual(a.obstacles,b.obstacles);assert.notDeepEqual(a.obstacles,c.obstacles);assert.ok(a.obstacles.length>60);for(const o of a.obstacles)assert.ok(Math.hypot(o.x-1200,o.y-1200)>210)});
test('movement collides with terrain and world borders',()=>{const w=createWorld(42),o=w.obstacles[0],e={x:o.x-o.r-14,y:o.y,r:13};moveEntity(e,20,0,w);assert.ok(distance(e,o)>=e.r+o.r-.001);moveEntity(e,-10000,0,w);assert.ok(e.x>=e.r)});
test('auto fire damages enemies and kills drop collectible experience',()=>{const g=fresh();g.spawn('crawler',1290,1200);tick(g,2);assert.equal(g.kills,1);assert.ok(g.gems.some(x=>!x.encounterId)||g.player.xp>0)});
test('enemy melee AI attacks and invulnerability blocks repeated damage',()=>{const g=fresh();g.player.attackRate=.01;g.fireClock=100;g.spawn('crawler',1225,1200);tick(g,2);assert.ok(g.player.hp<100);const hp=g.player.hp;g.player.invincible=1;g.hurt(10);assert.equal(g.player.hp,hp)});
test('ranged enemies telegraph then fire projectiles',()=>{const g=fresh();g.fireClock=100;g.spawn('shaman',1400,1200);tick(g,3);assert.ok(g.hostile.length>0)});
test('level up freezes world, offers three unique choices and applies selection once',()=>{const g=fresh();g.player.xp=12;g.checkLevel();assert.equal(g.state,'levelup');assert.equal(new Set(g.choices.map(c=>c.skill.id)).size,3);const t=g.time;g.step(.05);assert.equal(t,g.time);assert.ok(g.choose(0));assert.equal(g.state,'playing');assert.equal(g.choose(0),false);assert.equal(Object.keys(g.owned).length,1)});
test('multi projectile makes three fireballs; rarity sampling covers all tiers',()=>{const g=fresh();SKILLS.find(s=>s.id==='multi').apply(g.player,1);g.spawn('brute',1350,1200);g.shoot();assert.equal(g.shots.length,3);const tiers=new Set(),rng=seeded(4);for(let i=0;i<100;i++)rollChoices(rng).forEach(c=>tiers.add(c.rarity));assert.equal(tiers.size,3)});
test('boss spawns at 180 seconds, attacks, and death completes the run',()=>{const g=fresh();g.time=179.99;g.step(1/60);assert.ok(g.boss);g.player.invincible=100;tick(g,5);assert.ok(g.hostile.length||g.zones.length);g.hitEnemy(g.boss,100000);assert.equal(g.state,'won')});
test('death, pause and restart isolate run state',()=>{const g=fresh();g.pause();const t=g.time;g.step(.05);assert.equal(t,g.time);g.pause();g.hurt(200);assert.equal(g.state,'dead');g.reset(5);assert.equal(g.player.hp,100);assert.equal(g.kills,0);assert.equal(g.hostile.length,0);assert.equal(g.state,'playing')});
test('dash grants short invulnerability and respects cooldown',()=>{const g=fresh();assert.equal(g.dash(),true);assert.equal(g.dash(),false);g.hurt(50);assert.equal(g.player.hp,100);tick(g,3.1);assert.equal(g.dash(),true)});
test('full run simulation stays bounded, supports repeated upgrades and reaches boss',()=>{const g=fresh();g.spawnClock=0;g.player.maxHp=100000;g.player.hp=100000;for(let i=0;i<60*230;i++){const a=i/60*.08;g.step(1/60,{x:Math.cos(a),y:Math.sin(a)});if(g.state==='levelup')g.choose(0)}assert.ok(g.bossSpawned);assert.ok(g.player.level>1);assert.ok(g.enemies.length<=MAX_ENEMIES+1);assert.ok(g.particles.length<=MAX_PARTICLES);assert.ok(g.hostile.length<=220);assert.ok(Number.isFinite(g.player.x))});
test('enemy state machine exposes pursue, windup and recovery states',()=>{const g=fresh();g.fireClock=100;const e=g.spawn('crawler',1260,1200);g.step(1/60);assert.ok([ENEMY_STATES.PURSUE,ENEMY_STATES.RECOVER].includes(e.state));e.x=1225;e.y=1200;e.cooldown=0;g.step(1/60);assert.equal(e.state,ENEMY_STATES.WINDUP);tick(g,.5);assert.equal(e.state,ENEMY_STATES.RECOVER)});
test('skill synergies activate from owned skill combinations and change combat modifiers',()=>{const owned={multi:{count:1},blast:{count:1},frost:{count:1},pierce:{count:1},orbit:{count:1},ward:{count:1}};const active=getActiveSynergies(owned);assert.equal(active.length,3);const mods=getSynergyModifiers(owned);assert.ok(mods.splashDamage>1);assert.ok(mods.slowedDirect>1);assert.ok(mods.orbitDamage>1)});
test('choosing a completing skill emits a synergy awakening once',()=>{const events=[];const g=new Game({seed:42,onEvent:(type,data)=>events.push({type,data})});g.reset(42);const multi=SKILLS.find(s=>s.id==='multi'),blast=SKILLS.find(s=>s.id==='blast');g.state='levelup';g.choices=[{skill:multi,rarity:'rare'}];assert.ok(g.choose(0));g.state='levelup';g.choices=[{skill:blast,rarity:'common'}];assert.ok(g.choose(0));assert.ok(g.activeSynergyIds.has('volatile-volley'));assert.equal(events.filter(e=>e.type==='synergy'&&e.data.id==='volatile-volley').length,1)});
test('procedural encounters are seeded, clear of the start, and resolve into real rewards',()=>{const w=createWorld(42),a=createEncounters(42,w),b=createEncounters(42,w);assert.deepEqual(a,b);assert.equal(a.length,3);for(const e of a)assert.ok(Math.hypot(e.x-1200,e.y-1200)>330);const events=[];const g=new Game({seed:42,onEvent:(type,data)=>events.push({type,data})});g.reset(42);g.spawnClock=1000;const first=g.encounters[0],marker=g.gems.find(x=>x.encounterId===first.id),max=g.player.maxHp;g.player.x=marker.x;g.player.y=marker.y;g.step(1/60);assert.equal(first.resolved,true);assert.equal(g.player.maxHp,max+8);assert.equal(g.gems.some(x=>x.encounterId===first.id),false);assert.ok(events.some(e=>e.type==='encounter'&&e.data.id===first.id))});
test('runner and shaman expose distinct movement states instead of generic pursuit',()=>{const g=fresh();g.fireClock=100;const runner=g.spawn('runner',1450,1200),shaman=g.spawn('shaman',1500,1200);runner.cooldown=2;shaman.cooldown=2;g.step(1/60);assert.equal(runner.state,ENEMY_STATES.FLANK);assert.equal(shaman.state,ENEMY_STATES.KITE)});
test('runner charges from extended range while brute uses a slower heavy windup',()=>{const g=fresh();g.fireClock=100;const runner=g.spawn('runner',1370,1200);runner.cooldown=0;g.step(1/60);assert.equal(runner.state,ENEMY_STATES.WINDUP);const runnerWindup=runner.attack;const brute=g.spawn('brute',1285,1200);brute.cooldown=0;g.step(1/60);assert.equal(brute.state,ENEMY_STATES.WINDUP);assert.ok(brute.attack>runnerWindup)});
test('boss transitions through three health phases and emits phase events once',()=>{const events=[];const g=new Game({seed:42,onEvent:(type,data)=>events.push({type,data})});g.reset(42);g.spawnClock=1000;g.fireClock=100;g.player.invincible=100;const boss=g.spawn('boss',1500,1200);g.boss=boss;g.bossSpawned=true;g.step(1/60);assert.equal(boss.bossStage,BOSS_PHASES.AWAKENED);boss.hp=boss.maxHp*.65;g.step(1/60);assert.equal(boss.bossStage,BOSS_PHASES.ENRAGED);boss.hp=boss.maxHp*.32;g.step(1/60);assert.equal(boss.bossStage,BOSS_PHASES.LAST_STAND);assert.equal(events.filter(e=>e.type==='bossPhase').length,2)});
test('boss attack cadence escalates as phases advance',()=>{const e={bossStage:1};const w1=bossWindup(e),c1=bossCooldown(e);e.bossStage=2;const w2=bossWindup(e),c2=bossCooldown(e);e.bossStage=3;const w3=bossWindup(e),c3=bossCooldown(e);assert.ok(w1>w2&&w2>w3);assert.ok(c1>c2&&c2>c3)});
test('encounter presentation makes all three exploration targets visually distinct',()=>{const entries=['emberShrine','lostCache','ashAltar'].map(type=>getEncounterPresentation({type}));assert.equal(new Set(entries.map(x=>x.glyph)).size,3);assert.equal(new Set(entries.map(x=>x.accent)).size,3)});
