import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../dist/js/engine.js';
import {ACTIVE_GEMS,SUPPORT_GEMS,createLinks,configureLink,compileSkill,compatible,GEM_PRESETS} from '../dist/js/gems.js';
import {makePlayer} from '../dist/js/data.js';
import {castSkill,updateProjectiles,damageWithEffects} from '../dist/js/combat.js';
import {BOSS_ROSTER,resolveExtraAttack} from '../dist/js/monsters.js';
function fresh(){const g=new Game({seed:42});g.reset(42);g.spawnClock=1000;g.castClocks=[1000,1000,1000];return g}
function tick(g,n){for(let i=0;i<n*60;i++)g.step(1/60)}
const stats=(id,supports=[])=>compileSkill({active:id,supports},makePlayer());
test('all presets have unique gems and compatible sockets',()=>{for(const p of Object.values(GEM_PRESETS)){const seen=new Set();assert.equal(new Set(p.links.map(r=>r.active)).size,3);for(const r of p.links)for(const id of r.supports){assert.ok(compatible(r.active,id));assert.ok(!seen.has(id));seen.add(id)}}});
test('support changes are local, reject duplicates and invalid tag combinations',()=>{const links=createLinks(),before=compileSkill(links[1],makePlayer());assert.equal(configureLink(links,0,'support',0,'multi').ok,true);assert.equal(configureLink(links,0,'support',2,'chain').ok,true);assert.equal(configureLink(links,0,'support',1,null).ok,true);assert.equal(configureLink(links,0,'support',2,'fork').ok,true);assert.deepEqual(compileSkill(links[1],makePlayer()),before);const s=compileSkill(links[0],makePlayer());assert.equal(s.count,3);assert.equal(s.fork,true);assert.equal(s.pierce,0);assert.ok(s.damage<24)});
test('changing active installs in a free socket and game enforces pause',()=>{const g=fresh();assert.equal(g.configure(0,'active',0,'meteor').ok,false);g.bag.active.push('meteor');g.pause();assert.equal(g.configure(0,'active',0,'meteor').ok,true);assert.deepEqual(g.links[0].sockets,[{kind:'active',id:'meteor'},null,null,null]);const t=g.time;tick(g,2);assert.equal(g.time,t);g.reset(51);assert.equal(g.links[0].active,'fireball');assert.deepEqual(g.gemLevels,{})});
test('all direct active skills deal damage in their appropriate range',()=>{for(const id of Object.keys(ACTIVE_GEMS).filter(id=>!ACTIVE_GEMS[id].aura&&!ACTIVE_GEMS[id].trail)){const g=fresh();const e=g.spawn('brute',id==='orbit'?1276:1300,1200);e.hp=e.maxHp=10000;g.links=[{active:id,supports:[]}];g.castClocks=[0];const before=e.hp;tick(g,2);assert.ok(e.hp<before,`${id} should hit`);assert.ok(g.effects.length<=90)}});
test('chain lightning jumps to distinct enemies',()=>{const g=fresh();const enemies=[1300,1350,1400,1450,1500].map(x=>g.spawn('brute',x,1200));castSkill(g,stats('arc',['chain']));assert.equal(enemies.filter(e=>e.hp<e.maxHp).length,5);assert.equal(g.effects.length,5);assert.ok(enemies[4].hp>enemies[0].hp)});
test('fork creates two child projectiles and cannot fork recursively',()=>{const g=fresh(),e=g.spawn('brute',1230,1193);castSkill(g,stats('fireball',['fork']));g.grid.add(e);updateProjectiles(g,.04);assert.equal(g.shots.length,2);assert.ok(g.shots.every(s=>s.fork===false&&s.hit.has(e.id)));assert.ok(g.shots.every(s=>s.damage===24*.6))});
test('echo schedules one additional cast and consumes the queue',()=>{const g=fresh();g.links=[{active:'fireball',supports:['echo']}];g.castClocks=[0];g.spawn('brute',1400,1200);tick(g,.1);assert.equal(g.echoes.length,1);tick(g,.25);assert.equal(g.echoes.length,0);assert.equal(g.shots.length,2)});
test('ignite damages over time, leech is capped, execute works on bosses',()=>{const g=fresh();g.player.hp=50;const e=g.spawn('brute',1350,1200);damageWithEffects(g,e,20,stats('fireball',['burn','leech']));assert.ok(g.player.hp>50);const hp=e.hp;tick(g,1);assert.ok(e.hp<hp);g.player.hp=20;for(let i=0;i<20;i++){const e=g.spawn('brute',1300,1200);damageWithEffects(g,e,100,stats('fireball',['leech']))}assert.ok(g.player.hp<=28.001);g.summonBoss('frostBoss');g.boss.hp=2;damageWithEffects(g,g.boss,1,stats('arc',['execute']));while(g.state==='levelup')assert.equal(g.choose(0),true);assert.equal(g.state,'reward')});
test('all three boss variants have attacks and can complete the run',()=>{for(const type of BOSS_ROSTER){const g=fresh();g.summonBoss(type);assert.equal(g.boss.type,type);g.player.invincible=100;let attacked=false;for(let i=0;i<7*60;i++){g.step(1/60);attacked ||= g.hostile.length>0||g.zones.length>0||g.enemies.length>1}assert.ok(attacked,`${type} has attacks`);g.hitEnemy(g.boss,100000);while(g.state==='levelup')assert.equal(g.choose(0),true);assert.equal(g.state,'reward');assert.equal(g.rewardOptions.length,3)}});
test('charger hits, spitter poisons and summoner creates enemies',()=>{let g=fresh();g.spawn('charger',1400,1200);tick(g,3);assert.ok(g.player.hp<100);g=fresh();g.spawn('spitter',1370,1200);tick(g,3);assert.ok(g.zones.length>0);assert.ok(g.player.hp<100);g=fresh();g.spawn('summoner',1420,1200);tick(g,3);assert.ok(g.enemies.some(e=>e.type==='runner'))});
test('full-run stress with each preset keeps all effect queues bounded',()=>{for(const preset of Object.values(GEM_PRESETS)){const g=fresh();g.links=createLinks(preset.links);g.castClocks=[0,0,0];g.spawnClock=0;g.player.hp=g.player.maxHp=100000;for(let i=0;i<60*200;i++){g.step(1/60,{x:Math.cos(i/900),y:Math.sin(i/900)});if(g.state==='levelup')g.choose(0)}assert.ok(g.time>0);assert.ok(g.shots.length<=180);assert.ok(g.hostile.length<=220);assert.ok(g.meteors.length<=30);assert.ok(g.echoes.length<=30);assert.ok(g.effects.length<=90);assert.ok(g.zones.length<=70);assert.ok(g.player.level>=1)}});
